[greasyfork]
namespace = "https://greasyfork.org/users/1133279"
author = "Arylo"
homepage = "https://greasyfork.org/zh-CN/scripts/519936"
supportURL = "https://greasyfork.org/zh-CN/scripts/519936/feedback"
downloadURL = "https://update.greasyfork.org/scripts/519936/Set%20Fira%20Code%20as%20font%20in%20development%20websites.user.js"
updateURL = "https://update.greasyfork.org/scripts/519936/Set%20Fira%20Code%20as%20font%20in%20development%20websites.meta.js"
