author = "Arylo"

[greasyfork]
namespace = "https://greasyfork.org/users/1133279"
homepage = "https://greasyfork.org/scripts/567817"
supportURL = "https://greasyfork.org/scripts/567817/feedback"
downloadURL = "https://update.greasyfork.org/scripts/567817/Enhance%20the%20copy%20manga%20site.user.js"
updateURL = "https://update.greasyfork.org/scripts/567817/Enhance%20the%20copy%20manga%20site.meta.js"
