on:
  workflow_call:
    inputs:
      DOCKER_HUB_USERNAME:
        required: true
        type: string
    secrets:
      DOCKER_HUB_TOKEN:
        required: true

jobs:
  cron-exec:
    uses: ./.github/workflows/docker_image_action.yml
    with:
      FOLDER_NAME: cron-exec
      IMAGE_NAME: cron-exec
      IMAGE_TAGS: latest
      DOCKER_HUB_USERNAME: ${{ inputs.DOCKER_HUB_USERNAME }}
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
  restart-after-change:
    needs:
      - cron-exec
    if: always()
    uses: ./.github/workflows/docker_image_action.yml
    with:
      FOLDER_NAME: restart-after-change
      IMAGE_NAME: restart-after-change
      IMAGE_TAGS: latest
      FORCE_BUILD: ${{ needs.cron-exec.outputs.codeChange }}
      DOCKER_HUB_USERNAME: ${{ inputs.DOCKER_HUB_USERNAME }}
    secrets:
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
