name: Code Push

on:
  push:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: TS Type Check
        run: npx tsc --noEmit
      - name: Build Qinglong
        run: npm run build
      - name: Deploy Qinglong
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/qinglong
          branch: qinglong

