name: Code Push

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: TS Type Check
        run: npm run lint:type-check
      - name: Build Qinglong
        run: npm run build
      - name: Deploy Qinglong
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/qinglong
          branch: qinglong
      - name: Deploy Qinglong
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/monkey
          branch: monkey

