name: Code Push

on:
  - push
  - pull_request

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: TS Type Check
        run: npm run lint:type-check
      - name: Build Qinglong
        run: npm run build
      - name: Deploy Qinglong scripts
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/qinglong
          branch: qinglong
        if: github.ref_name == github.event.repository.default_branch
      - name: Deploy Monkey scripts
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/monkey
          branch: monkey
        if: github.ref_name == github.event.repository.default_branch

