on:
  workflow_call:

jobs:
  qinglong_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Build Scripts
        run: npm run build:qinglong
      - name: Deploy Qinglong scripts
        if: github.event_name == 'push' && github.ref_name == github.event.repository.default_branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/qinglong
          branch: qinglong
